#!/usr/bin/env python3
"""Write .github/dependencies/quality-tools/requirements.txt from pyproject.toml (direct pins only)."""

from __future__ import annotations

import tomllib
from pathlib import Path


def _root() -> Path:
    """Return the repository root directory (parent of ``scripts/``)."""
    return Path(__file__).resolve().parent.parent


def _groups_table(data: object) -> dict[str, object]:
    """Return the ``dependency-groups`` table from parsed ``pyproject.toml`` data."""
    if not isinstance(data, dict):
        raise SystemExit('pyproject.toml: invalid structure')

    groups = data.get('dependency-groups')
    if not isinstance(groups, dict):
        raise SystemExit('pyproject.toml: missing [dependency-groups]')

    return groups


def _quality_tools_entries(groups: dict[str, object]) -> list[str]:
    """Return PEP 508 requirement strings from the ``quality-tools`` dependency group."""
    qt = groups.get('quality-tools')
    if not isinstance(qt, list):
        raise SystemExit('pyproject.toml: missing quality-tools group')

    out: list[str] = []
    for item in qt:
        if not isinstance(item, str):
            raise SystemExit('quality-tools: only string pins allowed (no include-group here)')

        out.append(item)

    return out


def export_quality_tools_requirements(root: Path) -> None:
    """Write ``quality-tools/requirements.txt`` under ``root`` from ``[dependency-groups].quality-tools``."""
    raw = (root / 'pyproject.toml').read_text(encoding='utf-8')
    data = tomllib.loads(raw)
    lines = _quality_tools_entries(_groups_table(data))
    header = (
        '# Pinned CLI tools for python-quality.yml (uv tool install). '
        'Generated by scripts/export_quality_tools_requirements.py from pyproject.toml. '
        'Dependabot: uv, /'
    )
    text = '\n'.join([header, *lines]) + '\n'
    out = root / '.github' / 'dependencies' / 'quality-tools' / 'requirements.txt'
    out.write_text(text, encoding='utf-8')


def main() -> None:
    """CLI entrypoint: export pins for the current repository layout."""
    export_quality_tools_requirements(_root())


if __name__ == '__main__':
    main()
